
first = pow(vect_size(ray), 2) - pow(ray[X] * cy->o_vect[X], 2) - pow(ray[Y] * cy->o_vect[Y], 2) - pow(ray[Z] * cy->o_vect[Z], 2) - 2 * (ray[X] * ray[Y] *cy->o_vect[X] *cy->o_vect[Y] + ray[X] * ray[Z] * cy->o_vect[X] *cy->o_vect[Z] + ray[Y] * ray[Z] * cy->o_vect[Y] * cy->o_vect[Z]);
second = - 2 * (ray[X] * cy->center[X] + ray[Y] * cy->center[Y] + ray[Z] * cy->center[Z] - ray[X] *cy->center[X] * pow(cy->o_vect[X], 2) - ray[X] * cy->center[Y] * cy->o_vect[X] * cy->o_vect[Y] - ray[X] *cy->center[Z] * cy->o_vect[X] * cy->o_vect[Z] - ray[Y] * cy->center[X] * cy->o_vect[X] * cy->o_vect[Y] - ray[Y] * cy->center[Y] * pow(cy->o_vect[Y], 2) - ray[Y] * cy->center[Z] * cy->o_vect[Y] * cy->o_vect[Z] - ray[Z] * cy->center[X] * cy->o_vect[X] * cy->o_vect[Z] - ray[Z] * cy->center[Y] * cy->o_vect[Y] * cy->o_vect[Z] - ray[Z] * cy->center[Z] * pow(cy->o_vect[Z], 2));
third = pow(vect_size(cy->center), 2) - pow(cy->radius, 2) - pow(cy->center[X] * cy->o_vect[X], 2) - pow(cy->center[Y] * cy->o_vect[Y], 2) - pow(cy->center[Z] * cy->o_vect[Z], 2) - 2 * (cy->center[X] * cy->center[Y] * cy->o_vect[X] * cy->o_vect[Y] + cy->center[X] * cy->center[Z] * cy->o_vect[X] * cy->o_vect[Z] + cy->center[Y] * cy->center[Z] * cy->o_vect[Y] * cy->o_vect[Z];



first = pow(ray[X], 2) + pow(ray[Y], 2) + pow(ray[Z], 2) - pow(ray[X] * cy->o_vect[X], 2) - pow(ray[Y] * cy->o_vect[Y], 2) - pow(ray[Z] * cy->o_vect[Z], 2) - 2 * (ray[X] * ray[Y] *cy->o_vect[X] *cy->o_vect[Y] + ray[X] * ray[Z] * cy->o_vect[X] *cy->o_vect[Z] + ray[Y] * ray[Z] * cy->o_vect[Y] * cy->o_vect[Z])
second = - 2 * (ray[X] * cy->center[X] + ray[Y] * cy->center[Y] + ray[Z] * cy->center[Z] - ray[X] *cy->center[X] * pow(cy->o_vect[X], 2) - ray[X] * cy->center[Y] * cy->o_vect[X] * cy->o_vect[Y] - ray[X] *cy->center[Z] * cy->o_vect[X] * cy->o_vect[Z] - ray[Y] * cy->center[X] * cy->o_vect[X] * cy->o_vect[Y] - ray[Y] * cy->center[Y] * pow(cy->o_vect[Y], 2) - ray[Y] * cy->center[Z] * cy->o_vect[Y] * cy->o_vect[Z] - ray[Z] * cy->center[X] * cy->o_vect[X] * cy->o_vect[Z] - ray[Z] * cy->center[Y] * cy->o_vect[Y] * cy->o_vect[Z] - ray[Z] * cy->center[Z] * pow(cy->o_vect[Z], 2))
third = pow(cy->center[X], 2) + pow(cy->center[Y], 2) + pow(cy->center[Z], 2) - pow(cy->radius, 2) - pow(cy->center[X] * cy->o_vect[X], 2) - 2 cy->center[X] cy->center[Y] cy->o_vect[X] cy->o_vect[Y] - 2 cy->center[X] cy->center[Z] cy->o_vect[X] cy->o_vect[Z] - cy->center[Y]^2 cy->o_vect[Y]^2 - 2 cy->center[Y] cy->center[Z] cy->o_vect[Y] cy->o_vect[Z] - cy->center[Z]^2 cy->o_vect[Z]^2
